import assert from "node:assert/strict";
import { collectEventbriteEvents } from "../lib/eventbrite-pagination";
(async () => {
  let calls: any[] = [];
  const page = (n: number, count: number, more = n < count) => ({events:[{id:String(n)}], pagination:{page_number:n,page_count:count,has_more_items:more,continuation:'p'+(n+1)}});
  let r = await collectEventbriteEvents(async q => {calls.push(q); return page(calls.length,25);}, {status:'live'}, {allPages:true});
  assert.equal(r.events.length,25); assert.equal(r.retrieval.completeListing,true);
  assert.equal(calls[1].continuation,'p2'); assert.equal(calls[1].status,'live'); assert.equal(calls[1].page,undefined);
  assert.equal(calls.length,25);
  calls=[];
  r=await collectEventbriteEvents(async q => {calls.push(q); return page(calls.length,25);},{},{allPages:true,maxPages:2});
  assert.equal(r.retrieval.completeListing,false); assert.equal(r.retrieval.limitReached,true); assert.deepEqual(r.retrieval.nextRequest,{continuation:'p3'});
  r=await collectEventbriteEvents(async()=>page(1,1,false));
  assert.equal(r.retrieval.completeListing,true); assert.equal(r.retrieval.nextRequest,null);
  r=await collectEventbriteEvents(async()=>page(1,3));
  assert.equal(r.retrieval.completeListing,false); assert.equal(r.retrieval.pagesFetched,1);
  calls=[];
  r=await collectEventbriteEvents(async q=>{calls.push(q); return {events:[{id:String(q.page || 1)}], pagination:{page_number:q.page || 1,page_count:3}};},{},{allPages:true});
  assert.deepEqual(calls,[{}, {page:2}, {page:3}]); assert.equal(r.events.length,3);
  r=await collectEventbriteEvents(async()=>page(5,5,false),{continuation:'p5'},{allPages:true});
  assert.equal(r.retrieval.completeListing,false); assert.equal(r.retrieval.reachedEnd,true);
  await assert.rejects(()=>collectEventbriteEvents(async()=>({events:[],pagination:{has_more_items:true,continuation:'same'}}),{}, {allPages:true}),/no progress/);
  await assert.rejects(()=>collectEventbriteEvents(async()=>({events:[{id:'1'}],pagination:{has_more_items:true,continuation:'same'}}),{}, {allPages:true}),/no progress|repeated/);
  await assert.rejects(()=>collectEventbriteEvents(async()=>({events:[]})),/completeness is unknown/);
  await assert.rejects(()=>collectEventbriteEvents(async()=>({events:[{id:'1'}],pagination:{}})),/whether more pages/);
  await assert.rejects(()=>collectEventbriteEvents(async()=>({events:[{id:'1'}],pagination:{has_more_items:true}})),/no usable/);
  r=await collectEventbriteEvents(async()=>({events:[],pagination:{has_more_items:false,page_count:0,page_number:1}}));
  assert.equal(r.events.length,0); assert.equal(r.retrieval.completeListing,true);
  calls=[];
  r=await collectEventbriteEvents(async()=>{const n=++calls.length;return {events:n===1?[{id:'1'},{id:'2'}]:[{id:'2'},{id:'3'}],pagination:{page_number:n,page_count:2}};},{},{allPages:true});
  assert.equal(r.events.length,3);
  console.log('PASS: 13 pagination regression scenarios');
})().catch(e=>{ console.error(e); process.exit(1); });
