import type { ActivityDefinition, ApprovedPhoto } from "./types";

const VIP_DATE_NIGHT_PHOTO: ApprovedPhoto = {
  filename: "vip-date-night-painting.png",
  driveFileId: "",
  path: "/images/classes/vip-date-night-painting.png",
  width: 1448,
  height: 1086,
  alt: "Two guests painting winter birds on snowy branches at studio easels",
  focalPosition: "50% 50%",
};

const GLASS_FUSION_PHOTO: ApprovedPhoto = {
  filename: "glass-fusion.png",
  driveFileId: "acuity-79183146",
  path: "/images/classes/glass-fusion.png",
  width: 700,
  height: 699,
  alt: "Handmade fused glass artwork",
  focalPosition: "50% 50%",
};

export const APPROVED_IMAGE_FOLDER = "https://drive.google.com/drive/folders/17HDWG2QYM_POUbF61Gm_mk0OSn5Y9kxL";

export const APPROVED_PHOTOS: ApprovedPhoto[] = [
  {
    "filename": "Bonsai for Beginners: Hands-On Workshop - Chicago.webp",
    "driveFileId": "1313Zo8PU-B93TPrRK2BtgSa1PoHsW-Hv",
    "path": "/images/classes/approved-01-HsW-Hv-48dba9a4f983.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two workshop guests holding their finished bonsai trees",
    "focalPosition": "50% 42%"
  },
  {
    "filename": "Boobs Coffee Mug - Chicago.webp",
    "driveFileId": "1doXJBmxsZonqysNYO4wPZdV8lFOxXCRA",
    "path": "/images/classes/approved-02-OxXCRA-483d78af789f.webp",
    "width": 1080,
    "height": 810,
    "alt": "A participant shaping a body-inspired clay mug",
    "focalPosition": "55% 45%"
  },
  {
    "filename": "Candle Making - Chicago.webp",
    "driveFileId": "1ItqqGer2N5dAJOOwWlhejDm0Ew3xOd0G",
    "path": "/images/classes/approved-03-3xOd0G-3b868ddea3a9.webp",
    "width": 1200,
    "height": 900,
    "alt": "A candle-making instructor helping guests at a studio worktable",
    "focalPosition": "48% 45%"
  },
  {
    "filename": "Cat Vase Making - Chicago.webp",
    "driveFileId": "1nmmfhUOfn-Xg7N37pWpo1coU7Nbvze7K",
    "path": "/images/classes/approved-04-bvze7K-ec006f49f9b6.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two guests showing their handbuilt cat vases",
    "focalPosition": "50% 40%"
  },
  {
    "filename": "Ceramic Mug and a Bowl - Chicago.webp",
    "driveFileId": "1WtKmP1ivyyj2SBnF1N1FlXOfKB9-c5wW",
    "path": "/images/classes/approved-05-9-c5wW-833640afcace.webp",
    "width": 1084,
    "height": 813,
    "alt": "A participant handbuilding pottery at a clay-covered studio table",
    "focalPosition": "60% 50%"
  },
  {
    "filename": "Charcuterie Board Make And Paint.webp",
    "driveFileId": "1v0FlW6PrKA5r_dok6WSSXmLVyUJv3ZHw",
    "path": "/images/classes/approved-06-Jv3ZHw-c93bf2f3ff95.webp",
    "width": 984,
    "height": 738,
    "alt": "A decorated ceramic serving board arranged with food",
    "focalPosition": "50% 55%"
  },
  {
    "filename": "Chicago Date Night Pottery.webp",
    "driveFileId": "194clPBzrJEB4A7mrJkYSNlPfzmGo6xn9",
    "path": "/images/classes/approved-07-Go6xn9-08daf172fdf1.webp",
    "width": 680,
    "height": 510,
    "alt": "A couple working together on clay at a pottery wheel",
    "focalPosition": "48% 55%"
  },
  {
    "filename": "Date Night Bonsai VIP.webp",
    "driveFileId": "1ipWUtg4iAI2BYOHlTPv-ozBkePjaP3Wk",
    "path": "/images/classes/approved-08-jaP3Wk-48dba9a4f983.webp",
    "width": 1200,
    "height": 900,
    "alt": "A couple holding bonsai trees made in their workshop",
    "focalPosition": "50% 42%"
  },
  {
    "filename": "Date Night Candle Making.webp",
    "driveFileId": "1RmziT-exXIMkDpnckW4ByH2RtfpGZ8Xc",
    "path": "/images/classes/approved-09-pGZ8Xc-f80ab73cab4c.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two guests smiling at a candle-making workshop table",
    "focalPosition": "50% 40%"
  },
  {
    "filename": "Date Night On Fire - VIP EXPERIENCE.webp",
    "driveFileId": "1r7cdx8xM97TKHY7yrmIM4W3bRM0WVDdt",
    "path": "/images/classes/approved-10-0WVDdt-8552826d25e5.webp",
    "width": 1200,
    "height": 900,
    "alt": "Hands shaping a tall clay vessel on a pottery wheel",
    "focalPosition": "52% 65%"
  },
  {
    "filename": "Date Night Watercolor Painting for Two - Chicago.webp",
    "driveFileId": "1pG8c-BNS5LsGxlAILx-fZZgM4rPKrRG-",
    "path": "/images/classes/approved-11-PKrRG--1250486ab1dc.webp",
    "width": 940,
    "height": 705,
    "alt": "Watercolor flowers beside a watercolor palette and brushes",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Date Night Watercolor Painting for Two - Eugene.webp",
    "driveFileId": "1JPYwvGbQTLtgs53G-8xmIxa-tcFB2XmA",
    "path": "/images/classes/approved-12-FB2XmA-1250486ab1dc.webp",
    "width": 940,
    "height": 705,
    "alt": "Watercolor flowers beside a watercolor palette and brushes",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Date Night: Make Your Own Ceramic Chess Set ♟️.webp",
    "driveFileId": "1tH32y2VynWe1KrhuygbBMcARm7zfKHQr",
    "path": "/images/classes/approved-13-zfKHQr-b484e7f234e3.webp",
    "width": 1200,
    "height": 900,
    "alt": "Handmade blue and gold ceramic chess pieces",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Dildos and Bottles - Chicago.webp",
    "driveFileId": "1A0z3iSQIrVgzc0GDYG9UurcYUaO6jPqj",
    "path": "/images/classes/approved-14-O6jPqj-44b6e46c35f2.webp",
    "width": 1200,
    "height": 900,
    "alt": "A group working on adult-themed clay projects in the studio",
    "focalPosition": "50% 43%"
  },
  {
    "filename": "Eugene : Make Your Own Charcuterie Board.webp",
    "driveFileId": "1n4kaRbWpiTajJmNi1f-vK3KYFfGUmXbp",
    "path": "/images/classes/approved-15-GUmXbp-c93bf2f3ff95.webp",
    "width": 984,
    "height": 738,
    "alt": "A ceramic serving board arranged with fruit and cheese",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Eugene 🌿 Date Night Terrarium Workshop.webp",
    "driveFileId": "1-TTFdz3-dOIFw7_KSVjMP6mfxSbe3SrC",
    "path": "/images/classes/approved-16-be3SrC-424e14c07efd.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two guests arranging plants in terrarium containers",
    "focalPosition": "48% 50%"
  },
  {
    "filename": "Eugene Date Night On The Wheel.webp",
    "driveFileId": "1iQ4dV0SfOR30yj6_-5IUKkfq8ih_HdFG",
    "path": "/images/classes/approved-17-h_HdFG-66253a9801df.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two guests shaping clay together at a pottery wheel",
    "focalPosition": "50% 58%"
  },
  {
    "filename": "Eugene Duck Soap holder.webp",
    "driveFileId": "1F6_m5BS08ufMK-lkDrUvOPMCU7iHzJZB",
    "path": "/images/classes/approved-18-iHzJZB-062e8f625073.webp",
    "width": 1200,
    "height": 900,
    "alt": "A white ceramic duck-shaped soap holder",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Eugene Mushroom Pottery.webp",
    "driveFileId": "1_05XYf1Ttn-mFsrVPOozD6GhnxLiMP2x",
    "path": "/images/classes/approved-19-LiMP2x-4c03060fd117.webp",
    "width": 1200,
    "height": 900,
    "alt": "A handmade clay bowl decorated with little mushrooms",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Eugene Pipe and Ashtray Making Class.webp",
    "driveFileId": "1A_Uc_Pcuvzlit2-czndlYINfa5bxE6AT",
    "path": "/images/classes/approved-20-bxE6AT-5987c695c8b3.webp",
    "width": 1200,
    "height": 900,
    "alt": "Guests sculpting clay at a shared studio table",
    "focalPosition": "50% 45%"
  },
  {
    "filename": "Eugene Wheel Throwing for Beginners: Cup creations.webp",
    "driveFileId": "1GPlEk3mPWnLxi_mUfgrXocT4eNe-GdkT",
    "path": "/images/classes/approved-21-e-GdkT-20ed285cc994.webp",
    "width": 1200,
    "height": 900,
    "alt": "A smiling workshop guest holding a freshly made clay cup",
    "focalPosition": "50% 42%"
  },
  {
    "filename": "Eugene Wheel Throwing for Beginners: Matcha Bowl.webp",
    "driveFileId": "1X5DfJL0Sy3ohFrMsh5YpXMv6s8jhPcfu",
    "path": "/images/classes/approved-22-jhPcfu-9847496ddb3a.webp",
    "width": 1152,
    "height": 864,
    "alt": "A handmade ceramic matcha bowl with a pouring lip",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Eugene: Ceramic Mug and a Bowl.webp",
    "driveFileId": "1SPxv3rAsMNN-AQPI_PHvkIauuPoFSphW",
    "path": "/images/classes/approved-23-oFSphW-833640afcace.webp",
    "width": 1084,
    "height": 813,
    "alt": "A participant handbuilding pottery at a clay-covered studio table",
    "focalPosition": "60% 50%"
  },
  {
    "filename": "FLASH SALE BEGINNERS WHEEL THROWING.webp",
    "driveFileId": "1us6KmXl90xq-GVC7Ik5dWGjA511Xe4O7",
    "path": "/images/classes/wheel-throwing-for-beginners-color-cocktail-factory-acuity-600x600.jpg",
    "width": 600,
    "height": 600,
    "alt": "Students shaping clay on pottery wheels during a beginner workshop",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Halloween Ghost Pottey!.webp",
    "driveFileId": "1YMDM6UHHdSUwyX-x1plX-S3jWFXp8VJh",
    "path": "/images/classes/approved-25-Xp8VJh-a3cc50ff33d0.webp",
    "width": 1200,
    "height": 900,
    "alt": "Three studio guests holding handmade clay ghosts",
    "focalPosition": "50% 48%"
  },
  {
    "filename": "Halloween Pottery: Carve Your Own Clay Pumpkin.webp",
    "driveFileId": "10AJ_Mn1-NZrWPUDPixT_VsunIflimpFo",
    "path": "/images/classes/approved-26-limpFo-fc92c5a6a49d.webp",
    "width": 1084,
    "height": 813,
    "alt": "A participant carving a face into a clay pumpkin",
    "focalPosition": "55% 53%"
  },
  {
    "filename": "Handbuilding For Beginners - Vase Making.webp",
    "driveFileId": "1bIBAAXJhbKNQdOGTT48BtbybBvOd_yaM",
    "path": "/images/classes/approved-27-Od_yaM-db5f47ec152e.webp",
    "width": 1120,
    "height": 840,
    "alt": "Two guests holding their handbuilt pottery vases",
    "focalPosition": "50% 45%"
  },
  {
    "filename": "Hanging Turkish Mosaic Lamp - Chicago.webp",
    "driveFileId": "1B5ASopfJkDaFOKzxCzNnTrGsp6k53Mrx",
    "path": "/images/classes/approved-28-k53Mrx-cda788618ed1.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two workshop guests with colorful mosaic lamps",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Make a Clay Cauldron — Live Online Halloween Workshop.webp",
    "driveFileId": "1GrTH8xrgkUTKM98nw0XjfIn6TBmzv-ST",
    "path": "/images/classes/approved-29-mzv-ST-49bec5c931b2.webp",
    "width": 1200,
    "height": 900,
    "alt": "A black clay cauldron with small handles",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Make And Paint - Wheel throwing.webp",
    "driveFileId": "1ZmRBxXpBVYiOVsHyJy-k2T4DDoMWLugH",
    "path": "/images/classes/approved-30-MWLugH-4fd2082da220.webp",
    "width": 1044,
    "height": 783,
    "alt": "Participants painting pottery on wheels in the studio",
    "focalPosition": "50% 60%"
  },
  {
    "filename": "MONSTER POTTERY! HALLOWEEN LANTERN CLASS.webp",
    "driveFileId": "1m8h0_RuVEIusnYBoRCVjTLVdSu-C-m2D",
    "path": "/images/classes/approved-31--C-m2D-9bb1c21ffb08.webp",
    "width": 1120,
    "height": 840,
    "alt": "Hands sculpting a clay monster lantern",
    "focalPosition": "52% 55%"
  },
  {
    "filename": "Mosaic Creations - Chicago.webp",
    "driveFileId": "1Ie2yRdR3PyUJq5UYwFI9adlehgrW3n0V",
    "path": "/images/classes/approved-32-rW3n0V-cadbf04e7dff.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two guests showing their colorful mosaic creations",
    "focalPosition": "50% 45%"
  },
  {
    "filename": "Mushroom Pottery - Chicago.webp",
    "driveFileId": "1ASVnYO-DEJjWKu2IV5_54cuI6TcnT_gx",
    "path": "/images/classes/approved-33-cnT_gx-4c03060fd117.webp",
    "width": 1200,
    "height": 900,
    "alt": "A handmade clay bowl decorated with little mushrooms",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "OOGIE BOOGIE INSPIRED CANDLE HOLDER | HALLOWEEN POTTERY.webp",
    "driveFileId": "1Dk1vbnkzI5CVqE5sqrNzI28vJFB1jIP2",
    "path": "/images/classes/approved-34-B1jIP2-7da4f1254f0e.webp",
    "width": 1080,
    "height": 810,
    "alt": "Two sculpted Oogie Boogie-inspired clay candle holders",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Open Studio Wheel throwing.webp",
    "driveFileId": "1aMKNGVj2QaG3s8qol35P5JcEUoa5mSV-",
    "path": "/images/classes/approved-35-a5mSV--31ce8e8ba7af.webp",
    "width": 1120,
    "height": 840,
    "alt": "A potter shaping a bowl at an open studio wheel",
    "focalPosition": "55% 60%"
  },
  {
    "filename": "Paint Pottery - Chicago.webp",
    "driveFileId": "1N4Smjtmki9ib-oTL2xL8ipQCL4hnfruv",
    "path": "/images/classes/approved-36-hnfruv-c1631ba91192.webp",
    "width": 816,
    "height": 612,
    "alt": "Pottery painting at the studio and examples of painted plates",
    "focalPosition": "50% 52%"
  },
  {
    "filename": "Pipe and Ashtray Making Class - Chicago.webp",
    "driveFileId": "1Gf3pMDTNEgJgY20r4Twg1MvYODZmbGc9",
    "path": "/images/classes/approved-37-ZmbGc9-5987c695c8b3.webp",
    "width": 1200,
    "height": 900,
    "alt": "Guests sculpting clay at a shared studio table",
    "focalPosition": "50% 45%"
  },
  {
    "filename": "Pussy Pottery - Chicago.webp",
    "driveFileId": "1EubdimRySRYd_IYvDKPlbPZXE9qZICjD",
    "path": "/images/classes/approved-38-qZICjD-8bdf861bfae5.webp",
    "width": 1200,
    "height": 900,
    "alt": "An arrangement of body-inspired ceramic vessels",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Soap Making - Chicago.webp",
    "driveFileId": "1WgojxuIVC4kZfpAQoHeHda08iU6pd03D",
    "path": "/images/classes/approved-39-6pd03D-aa5367dfe912.webp",
    "width": 1180,
    "height": 885,
    "alt": "Handmade soap bars beside flowers and oils",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Spin A Spell- Make your Own Clay Cauldron.webp",
    "driveFileId": "1TQ1ahWNZted7uwQrvDmiM8IcFZmk2QuD",
    "path": "/images/classes/approved-40-mk2QuD-49bec5c931b2.webp",
    "width": 1200,
    "height": 900,
    "alt": "A black clay cauldron with small handles",
    "focalPosition": "50% 58%"
  },
  {
    "filename": "Throw A Pumpkin On The Wheel.webp",
    "driveFileId": "1QcgtqkhqZ-bmRZLel8UTmDdU40Z5t289",
    "path": "/images/classes/approved-41-Z5t289-fa4591214677.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two unglazed wheel-thrown clay pumpkins",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Turkish Mosaic Lamp - Chicago.webp",
    "driveFileId": "1WFd8fUpeTML-DZSu8gQ4-ViDpW9vzaFl",
    "path": "/images/classes/approved-42-9vzaFl-cda788618ed1.webp",
    "width": 1200,
    "height": 900,
    "alt": "Two workshop guests with colorful mosaic lamps",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "VIP DATE NIGHT PAINT NIGHT.webp",
    "driveFileId": "1Dd_VIg9xcKuRc17_F0kHIT1Gq068dhl8",
    "path": "/images/classes/approved-43-68dhl8-f05d61fb4af0.webp",
    "width": 1200,
    "height": 900,
    "alt": "A finished painting of colorful birds on tree branches",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Water Color For Beginners.webp",
    "driveFileId": "1GujlQ9QUHvUdMFJJoh_ajjyWdg-Yj9yC",
    "path": "/images/classes/approved-44--Yj9yC-1250486ab1dc.webp",
    "width": 940,
    "height": 705,
    "alt": "Watercolor flowers beside a watercolor palette and brushes",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Wheel Throwing for Beginners - Chicago.webp",
    "driveFileId": "1rUWLJ1sUh8iFBVU5xwI0CCmlO5e58mRd",
    "path": "/images/classes/wheel-throwing-for-beginners-color-cocktail-factory-acuity-600x600.jpg",
    "width": 600,
    "height": 600,
    "alt": "Students shaping clay on pottery wheels during a beginner workshop",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Wheel Throwing for Beginners -Cup Creations.webp",
    "driveFileId": "1jqsoqPsiLbjt0OKDsiEHxlArlXZzjDrH",
    "path": "/images/classes/approved-46-ZzjDrH-20ed285cc994.webp",
    "width": 1200,
    "height": 900,
    "alt": "A smiling workshop guest holding a freshly made clay cup",
    "focalPosition": "50% 42%"
  },
  {
    "filename": "Wheel Throwing for Beginners -Make Your Own Matcha Bowl.webp",
    "driveFileId": "1eK1meuDixOc_lZWYmGh78TTphwljxCA2",
    "path": "/images/classes/approved-47-ljxCA2-9847496ddb3a.webp",
    "width": 1152,
    "height": 864,
    "alt": "A handmade ceramic matcha bowl with a pouring lip",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Wheel Throwing for Beginners -Vase Making.webp",
    "driveFileId": "1ZxDIPV80lLYE8-YVvJ-rRNkPK7fzOd_M",
    "path": "/images/classes/approved-48-fzOd_M-78335159bcd7.webp",
    "width": 1200,
    "height": 900,
    "alt": "A participant shaping a clay vessel at a pottery wheel",
    "focalPosition": "50% 60%"
  },
  {
    "filename": "Wine Glass Painting - Chicago.webp",
    "driveFileId": "1GxySoZHJuUstkXWjY6Z8t2DE9hltrBKB",
    "path": "/images/classes/approved-49-ltrBKB-622409207453.webp",
    "width": 1200,
    "height": 900,
    "alt": "Colorfully painted wine glasses",
    "focalPosition": "50% 50%"
  },
  {
    "filename": "Wine Glass Painting.webp",
    "driveFileId": "1n0pbgfFdzGJsshozmSmAUZKedDDEuF4h",
    "path": "/images/classes/approved-50-DEuF4h-622409207453.webp",
    "width": 1200,
    "height": 900,
    "alt": "Colorfully painted wine glasses",
    "focalPosition": "50% 50%"
  }
];

export const ACTIVITY_MANIFEST: ActivityDefinition[] = [
  {
    "key": "chicago-cauldron",
    "title": "Cauldron Pottery",
    "description": "Make your own clay cauldron in a guided, beginner-friendly workshop.",
    "acuityTitle": "Spin A Spell- Make your Own Clay Cauldron",
    "appointmentTypeId": 95588506,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95588506",
    "priority": 5,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[39]
  },
  {
    "key": "eugene-cauldron",
    "title": "Cauldron Pottery",
    "description": "Make your own clay cauldron in a guided, beginner-friendly workshop.",
    "acuityTitle": "Spin A Spell- Make your Own Clay Cauldron",
    "appointmentTypeId": 96657402,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96657402",
    "priority": 5,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[39]
  },
  {
    "key": "chicago-date-night-wheel",
    "title": "Date Night Pottery on the Wheel",
    "description": "Share one wheel, make two pieces together.",
    "acuityTitle": "Date Night on the Pottery Wheel - Chicago",
    "appointmentTypeId": 79006071,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/date-night-wheel",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79006071",
    "priority": 6,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": "Visual review confirmed Chicago Date Night Pottery.webp depicts wheel throwing; the booking mapping was independently verified by appointment ID.",
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[6]
  },
  {
    "key": "eugene-date-night-wheel",
    "title": "Date Night Pottery on the Wheel",
    "description": "Share one wheel, make two pieces together.",
    "acuityTitle": "Eugene Date Night On The Wheel",
    "appointmentTypeId": 91935746,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": "/activities/date-night-wheel",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=91935746",
    "priority": 6,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[16]
  },
  {
    "key": "chicago-beginner-wheel",
    "title": "Wheel Throwing for Beginners",
    "description": "Try the pottery wheel and shape your first clay creation.",
    "acuityTitle": "Wheel Throwing for Beginners - Chicago",
    "appointmentTypeId": 79006616,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/beginner-wheel",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79006616",
    "priority": 1,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[44]
  },
  {
    "key": "eugene-cup-creations",
    "title": "Beginner Wheel: Cup Creations",
    "description": "Learn to center clay and throw your own cup on the wheel.",
    "acuityTitle": "Eugene Wheel Throwing for Beginners: Cup creations",
    "appointmentTypeId": 93539343,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=93539343",
    "priority": 1,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[20]
  },
  {
    "key": "chicago-turkish-lamp",
    "title": "Turkish Mosaic Lamp",
    "description": "Piece together colorful glass to make your own mosaic lamp.",
    "acuityTitle": "Turkish Mosaic Lamp - Chicago",
    "appointmentTypeId": 95416771,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/turkish-lamp",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95416771",
    "priority": 35,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[41]
  },
  {
    "key": "chicago-mug-and-bowl",
    "title": "Ceramic Mug and a Bowl",
    "description": "Handbuild a mug and bowl with your own finishing touches.",
    "acuityTitle": "Ceramic Mug and a Bowl - Chicago",
    "appointmentTypeId": 79186725,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79186725",
    "priority": 2,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[4]
  },
  {
    "key": "eugene-mug-and-bowl",
    "title": "Ceramic Mug and a Bowl",
    "description": "Handbuild a mug and bowl with your own finishing touches.",
    "acuityTitle": "Eugene: Ceramic Mug and a Bowl",
    "appointmentTypeId": 90210750,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=90210750",
    "priority": 2,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[22]
  },
  {
    "key": "chicago-terrarium",
    "title": "Terrarium Workshop",
    "description": "Build a little living garden with plants, moss, and decorative details.",
    "acuityTitle": "Terrarium Workshop - Chicago",
    "appointmentTypeId": 79189013,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/terrarium",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79189013",
    "priority": 16,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": "Shares the approved terrarium-workshop photograph with Eugene; appointment and ticket mappings remain separate.",
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[15]
  },
  {
    "key": "eugene-date-night-terrarium",
    "title": "Date Night Terrarium",
    "description": "Build miniature living gardens together in a guided workshop.",
    "acuityTitle": "Eugene 🌿 Date Night Terrarium Workshop",
    "appointmentTypeId": 89290193,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=89290193",
    "priority": 16,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": "Acuity describes date-night terrariums but also says ages 5–12. Confirm audience and ticket coverage before launch.",
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[15]
  },
  {
    "key": "chicago-mosaic",
    "title": "Mosaic Creations",
    "description": "Arrange colorful pieces into a mosaic of your own design.",
    "acuityTitle": "Mosaic Creations - Chicago",
    "appointmentTypeId": 79182319,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/mosaic",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79182319",
    "priority": 19,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[31]
  },
  {
    "key": "chicago-candle",
    "title": "Candle Making",
    "description": "Create and pour your own candle in a guided studio session.",
    "acuityTitle": "Candle Making - Chicago",
    "appointmentTypeId": 79185767,
    "calendarIds": [
      12216179,
      13582962
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79185767",
    "priority": 18,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[2]
  },
  {
    "key": "chicago-vip-paint-night",
    "title": "VIP Date Night Painting",
    "description": "Create a painting together with personal guidance from a studio artist.",
    "acuityTitle": "VIP DATE NIGHT PAINT NIGHT",
    "appointmentTypeId": 97020385,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97020385",
    "priority": 36,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": VIP_DATE_NIGHT_PHOTO
  },
  {
    "key": "eugene-vip-paint-night",
    "title": "VIP Date Night Painting",
    "description": "Create a painting together with personal guidance from a studio artist.",
    "acuityTitle": "VIP Date Night Paint Night",
    "appointmentTypeId": 94058109,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94058109",
    "priority": 36,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": VIP_DATE_NIGHT_PHOTO
  },
  {
    "key": "chicago-cat-vase",
    "title": "Cat Vase Making",
    "description": "Sculpt a clay vase with a cat-inspired face and ears.",
    "acuityTitle": "Cat Vase Making - Chicago",
    "appointmentTypeId": 79181599,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79181599",
    "priority": 3,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[3]
  },
  {
    "key": "chicago-clay-pumpkin",
    "title": "Clay Pumpkin Lantern",
    "description": "Handbuild and carve a clay pumpkin lantern with your own expression.",
    "acuityTitle": "Halloween Pottery: Carve Your Own Clay Pumpkin",
    "appointmentTypeId": 96889121,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96889121",
    "priority": 13,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[25]
  },
  {
    "key": "chicago-glass-fusion",
    "title": "Glass Fusion",
    "description": "Arrange colorful glass into your own fused-glass artwork.",
    "acuityTitle": "Glass Fusion - Chicago",
    "appointmentTypeId": 79183146,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/glass-fusion",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79183146",
    "priority": 22,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": "Official Acuity scheduler photograph supplied.",
    "verifiedAt": "2026-10-05",
    "image": GLASS_FUSION_PHOTO
  },
  {
    "key": "chicago-bonsai",
    "title": "Bonsai for Beginners",
    "description": "Shape and plant a miniature tree in a guided bonsai workshop.",
    "acuityTitle": "Bonsai for Beginners: Hands-On Workshop - Chicago",
    "appointmentTypeId": 79188910,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/bonsai",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79188910",
    "priority": 15,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[0]
  },
  {
    "key": "chicago-date-night-on-fire",
    "title": "Date Night on Fire",
    "description": "Share a VIP pottery experience together at the wheel.",
    "acuityTitle": "Date Night On Fire - VIP EXPERIENCE",
    "appointmentTypeId": 95023345,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95023345",
    "priority": 17,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[9]
  },
  {
    "key": "chicago-paint-pottery",
    "title": "Paint Your Own Pottery",
    "description": "Choose colors and paint your own ceramic piece.",
    "acuityTitle": "Paint Pottery - Chicago",
    "appointmentTypeId": 79183668,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79183668",
    "priority": 20,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[35]
  },
  {
    "key": "chicago-wine-glass-painting",
    "title": "Wine Glass Painting",
    "description": "Paint your own design on a wine glass.",
    "acuityTitle": "Wine Glass Painting - Chicago",
    "appointmentTypeId": 79374003,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": "/activities/wine-glass-painting",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79374003",
    "priority": 37,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[48]
  },
  {
    "key": "eugene-wine-glass-painting",
    "title": "Wine Glass Painting",
    "description": "Paint your own design on a wine glass.",
    "acuityTitle": "Wine Glass Painting",
    "appointmentTypeId": 95909935,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": "/activities/wine-glass-painting",
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95909935",
    "priority": 37,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[49]
  },
  {
    "key": "chicago-mushroom",
    "title": "Mushroom Pottery",
    "description": "Make a clay piece with whimsical mushroom details.",
    "acuityTitle": "Mushroom Pottery - Chicago",
    "appointmentTypeId": 79188019,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79188019",
    "priority": 11,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[32]
  },
  {
    "key": "eugene-mushroom",
    "title": "Mushroom Pottery",
    "description": "Make a clay piece with whimsical mushroom details.",
    "acuityTitle": "Eugene Mushroom Pottery",
    "appointmentTypeId": 90532757,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=90532757",
    "priority": 11,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[18]
  },
  {
    "key": "chicago-watercolor",
    "title": "Watercolor for Beginners",
    "description": "Explore watercolor washes and brushwork with guided instruction.",
    "acuityTitle": "Water Color For Beginners",
    "appointmentTypeId": 95947521,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95947521",
    "priority": 23,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[43]
  },
  {
    "key": "eugene-watercolor",
    "title": "Watercolor for Beginners",
    "description": "Explore watercolor washes and brushwork with guided instruction.",
    "acuityTitle": "Water Color for beginners",
    "appointmentTypeId": 96478474,
    "calendarIds": [],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96478474",
    "priority": 23,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-review",
    "reviewNote": "The public appointment type has no assigned calendar. Verify scheduling before showing a booking card.",
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[43]
  },
  {
    "key": "chicago-matcha-bowl",
    "title": "Matcha Bowl on the Wheel",
    "description": "Throw and shape your own matcha bowl on the pottery wheel.",
    "acuityTitle": "Wheel Throwing for Beginners -Make Your Own Matcha Bowl",
    "appointmentTypeId": 94782793,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94782793",
    "priority": 7,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[46]
  },
  {
    "key": "eugene-matcha-bowl",
    "title": "Beginner Wheel: Matcha Bowl",
    "description": "Throw and shape your own matcha bowl on the pottery wheel.",
    "acuityTitle": "Eugene Wheel Throwing for Beginners: Matcha Bowl",
    "appointmentTypeId": 89287658,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=89287658",
    "priority": 7,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[21]
  },
  {
    "key": "chicago-date-night-candle",
    "title": "Date Night Candle Making",
    "description": "Make a candle each during a creative studio date together.",
    "acuityTitle": "Date Night Candle Making",
    "appointmentTypeId": 95415406,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95415406",
    "priority": 18,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[8]
  },
  {
    "key": "chicago-ghost",
    "title": "Ghost Pottery",
    "description": "Shape a playful ghost from clay with step-by-step guidance.",
    "acuityTitle": "Halloween Ghost Pottey!",
    "appointmentTypeId": 98180179,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98180179",
    "priority": 26,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[24]
  },
  {
    "key": "chicago-oogie-boogie",
    "title": "Oogie Boogie Candle Holder",
    "description": "Sculpt a characterful clay candle holder with a crooked grin.",
    "acuityTitle": "OOGIE BOOGIE INSPIRED CANDLE HOLDER | HALLOWEEN POTTERY",
    "appointmentTypeId": 97524789,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97524789",
    "priority": 14,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[33]
  },
  {
    "key": "eugene-oogie-boogie",
    "title": "Oogie Boogie Candle Holder",
    "description": "Sculpt a characterful clay candle holder with a crooked grin.",
    "acuityTitle": "OOGIE BOOGIE INSPIRED CANDLE HOLDER | HALLOWEEN POTTERY",
    "appointmentTypeId": 98908868,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98908868",
    "priority": 14,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[33]
  },
  {
    "key": "chicago-monster-lantern",
    "title": "Monster Lantern Pottery",
    "description": "Sculpt and carve a clay lantern with a monstrous personality.",
    "acuityTitle": "MONSTER POTTERY! HALLOWEEN LANTERN CLASS",
    "appointmentTypeId": 97573448,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97573448",
    "priority": 28,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[30]
  },
  {
    "key": "chicago-hanging-turkish-lamp",
    "title": "Hanging Turkish Mosaic Lamp",
    "description": "Design a hanging lamp with colorful glass mosaic patterns.",
    "acuityTitle": "Hanging Turkish Mosaic Lamp - Chicago",
    "appointmentTypeId": 79374537,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79374537",
    "priority": 35,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[27]
  },
  {
    "key": "chicago-date-night-handbuilding",
    "title": "Date Night Handbuilding",
    "description": "Shape pottery together by hand during a creative studio date.",
    "acuityTitle": "Chicago Date Night Pottery",
    "appointmentTypeId": 94930972,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94930972",
    "priority": 42,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "The filename Chicago Date Night Pottery depicts a wheel session; this handbuilding product needs a suitable photograph.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-charcuterie-board",
    "title": "Make & Paint a Charcuterie Board",
    "description": "Make and decorate a ceramic board for your table.",
    "acuityTitle": "Charcuterie Board Make And Paint",
    "appointmentTypeId": 96649100,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96649100",
    "priority": 8,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[5]
  },
  {
    "key": "eugene-charcuterie-board",
    "title": "Make Your Own Charcuterie Board",
    "description": "Shape a ceramic charcuterie board with your own details.",
    "acuityTitle": "Eugene : Make Your Own Charcuterie Board",
    "appointmentTypeId": 98845998,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98845998",
    "priority": 8,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[14]
  },
  {
    "key": "chicago-handbuilt-vase",
    "title": "Handbuilt Vase Making",
    "description": "Build and texture a clay vase by hand.",
    "acuityTitle": "Handbuilding For Beginners - Vase Making",
    "appointmentTypeId": 96491249,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96491249",
    "priority": 27,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[26]
  },
  {
    "key": "chicago-soap",
    "title": "Soap Making",
    "description": "Make your own soap in a guided hands-on workshop.",
    "acuityTitle": "Soap Making - Chicago",
    "appointmentTypeId": 79274876,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79274876",
    "priority": 39,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[38]
  },
  {
    "key": "eugene-duck-soap-holder",
    "title": "Duck Soap Holder",
    "description": "Sculpt a little duck-shaped holder for your soap.",
    "acuityTitle": "Eugene Duck Soap holder",
    "appointmentTypeId": 98334198,
    "calendarIds": [
      12216179
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98334198",
    "priority": 38,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[17]
  },
  {
    "key": "chicago-open-studio",
    "title": "Open Studio Wheel Throwing",
    "description": "Spend dedicated studio time working on the pottery wheel.",
    "acuityTitle": "Open Studio Wheel throwing",
    "appointmentTypeId": 95911163,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95911163",
    "priority": 40,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[34]
  },
  {
    "key": "chicago-cup-creations",
    "title": "Cup Creations on the Wheel",
    "description": "Learn to center clay and throw your own cup on the wheel.",
    "acuityTitle": "Wheel Throwing for Beginners -Cup Creations",
    "appointmentTypeId": 94782668,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94782668",
    "priority": 10,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[45]
  },
  {
    "key": "chicago-wheel-pumpkin",
    "title": "Pumpkin on the Wheel",
    "description": "Throw and shape a ceramic pumpkin on the pottery wheel.",
    "acuityTitle": "Throw A Pumpkin On The Wheel",
    "appointmentTypeId": 98548612,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98548612",
    "priority": 9,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[40]
  },
  {
    "key": "eugene-ceramic-chess",
    "title": "Date Night Ceramic Chess",
    "description": "Create your own ceramic chess set together.",
    "acuityTitle": "Date Night: Make Your Own Ceramic Chess Set ♟️",
    "appointmentTypeId": 97861588,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97861588",
    "priority": 24,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[12]
  },
  {
    "key": "chicago-date-night-watercolor",
    "title": "Date Night Watercolor for Two",
    "description": "Paint together with watercolor in a guided creative date.",
    "acuityTitle": "Date Night Watercolor Painting for Two - Chicago",
    "appointmentTypeId": 94935292,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94935292",
    "priority": 23,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[10]
  },
  {
    "key": "eugene-date-night-watercolor",
    "title": "Date Night Watercolor for Two",
    "description": "Paint together with watercolor in a guided creative date.",
    "acuityTitle": "Date Night Watercolor Painting for Two - Eugene",
    "appointmentTypeId": 94932997,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94932997",
    "priority": 23,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[11]
  },
  {
    "key": "eugene-date-night-bonsai",
    "title": "VIP Date Night Bonsai",
    "description": "Learn to shape bonsai together in a guided date-night workshop.",
    "acuityTitle": "Date Night Bonsai VIP",
    "appointmentTypeId": 94058299,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94058299",
    "priority": 15,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[7]
  },
  {
    "key": "chicago-wheel-vase",
    "title": "Vase Making on the Wheel",
    "description": "Learn to throw a vase and shape its silhouette on the wheel.",
    "acuityTitle": "Wheel Throwing for Beginners -Vase Making",
    "appointmentTypeId": 94782880,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94782880",
    "priority": 25,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[47]
  },
  {
    "key": "chicago-date-night-turkish-lamp",
    "title": "Date Night Turkish Mosaic Lamp",
    "description": "Create colorful Turkish mosaic lamps together.",
    "acuityTitle": "Date Night Turkish Mosaic Lamp - Chicago",
    "appointmentTypeId": 95894050,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95894050",
    "priority": 35,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": true,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[41]
  },
  {
    "key": "chicago-make-and-paint-wheel",
    "title": "Make & Paint on the Wheel",
    "description": "Throw a pottery piece and add your own painted details.",
    "acuityTitle": "Make And Paint - Wheel throwing",
    "appointmentTypeId": 95806344,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=95806344",
    "priority": 29,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[29]
  },
  {
    "key": "chicago-flash-sale-wheel",
    "title": "Flash Sale Beginner Wheel",
    "description": "Try the pottery wheel in a guided beginner class.",
    "acuityTitle": "FLASH SALE BEGINNERS WHEEL THROWING",
    "appointmentTypeId": 96113161,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96113161",
    "priority": 43,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "promotion-unconfirmed",
    "reviewNote": "Owner confirmation is needed before advertising this promotion.",
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[23]
  },
  {
    "key": "chicago-acuity-79186489",
    "title": "Ceramic Bunny Cup - Chicago",
    "description": "Explore this studio workshop.",
    "acuityTitle": "Ceramic Bunny Cup - Chicago",
    "appointmentTypeId": 79186489,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79186489",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-94782610",
    "title": "Wheel Throwing for Beginners -Make Your Own Plate Set",
    "description": "Discover the joy of pottery in this hands-on beginner wheel throwing class",
    "acuityTitle": "Wheel Throwing for Beginners -Make Your Own Plate Set",
    "appointmentTypeId": 94782610,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=94782610",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-96474464",
    "title": "Wheel Throwing for Beginners - Fat Belly Mugs",
    "description": "There’s something extra comforting about a chunky mug with a big round belly",
    "acuityTitle": "Wheel Throwing for Beginners - Fat Belly Mugs",
    "appointmentTypeId": 96474464,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96474464",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-97799262",
    "title": "Touch-n-Clay PlayDay",
    "description": "Private event Dildo Making + Glaze",
    "acuityTitle": "Touch-n-Clay PlayDay",
    "appointmentTypeId": 97799262,
    "calendarIds": [],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97799262",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-97804677",
    "title": "Date night Art Session",
    "description": "Looking to get away from the hustle and bustle",
    "acuityTitle": "Date night Art Session",
    "appointmentTypeId": 97804677,
    "calendarIds": [],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97804677",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-97904101",
    "title": "Date Night Chix",
    "description": "The cutest date night",
    "acuityTitle": "Date Night Chix",
    "appointmentTypeId": 97904101,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97904101",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-97929620",
    "title": "Private Date Night Experience",
    "description": "The Ultimate Date Experience",
    "acuityTitle": "Private Date Night Experience",
    "appointmentTypeId": 97929620,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97929620",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-98139196",
    "title": "Make a Jar! — Wheel Throwing + Lid Workshop.",
    "description": "Learn how to throw your very own ceramic jar AND make a lid that actually fits",
    "acuityTitle": "Make a Jar! — Wheel Throwing + Lid Workshop.",
    "appointmentTypeId": 98139196,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98139196",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-acuity-98323116",
    "title": "MAKE YOUR PET  IN CLAY",
    "description": "Your best friend",
    "acuityTitle": "MAKE YOUR PET  IN CLAY",
    "appointmentTypeId": 98323116,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98323116",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "eugene-acuity-89288998",
    "title": "Eugene Date Night by Candlelight: Mosaic Experience",
    "description": "Step into an intimate, candlelit studio and create something beautiful—together",
    "acuityTitle": "Eugene Date Night by Candlelight: Mosaic Experience",
    "appointmentTypeId": 89288998,
    "calendarIds": [],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=89288998",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "eugene-acuity-91154739",
    "title": "Eugene Make Your Own Matcha Bowl",
    "description": "As fun as it sounds",
    "acuityTitle": "Eugene Make Your Own Matcha Bowl",
    "appointmentTypeId": 91154739,
    "calendarIds": [],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=91154739",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "eugene-acuity-92719840",
    "title": "Mothers Day Wheel Share",
    "description": "Celebrate Mothers Date with us and learn a new skill for the Lovely woman in your life",
    "acuityTitle": "Mothers Day Wheel Share",
    "appointmentTypeId": 92719840,
    "calendarIds": [],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=92719840",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "eugene-acuity-92719951",
    "title": "Mothers Day Wheel Throwing for Beginners",
    "description": "Learn a new skill with the special woman in your life This is the classic pottery wheel class—made simple, fun, and totally beginner-friendly",
    "acuityTitle": "Mothers Day Wheel Throwing for Beginners",
    "appointmentTypeId": 92719951,
    "calendarIds": [],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": null,
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-review",
    "reviewNote": "Booking state or studio mapping requires review; no active homepage button.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "eugene-acuity-92720069",
    "title": "Eugene: Mothers Day Pottery Hand-building",
    "description": "You'll learn how to create a set of mugs and a bowl with the guidance of our expert tutor",
    "acuityTitle": "Eugene: Mothers Day Pottery Hand-building",
    "appointmentTypeId": 92720069,
    "calendarIds": [],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=92720069",
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "unknown-acuity-79003717",
    "title": "Private Appointment for Couples (Pottery on Wheel)",
    "description": "Get muddy with your favorite person in this hands-on private pottery wheel class for couples",
    "acuityTitle": "Private Appointment for Couples (Pottery on Wheel)",
    "appointmentTypeId": 79003717,
    "calendarIds": [],
    "city": "unknown",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": null,
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-review",
    "reviewNote": "Booking state or studio mapping requires review; no active homepage button.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "unknown-acuity-79003968",
    "title": "Private Appointment for One (Pottery Wheel)",
    "description": "Try your hand at wheel throwing in this beginner-friendly class",
    "acuityTitle": "Private Appointment for One (Pottery Wheel)",
    "appointmentTypeId": 79003968,
    "calendarIds": [],
    "city": "unknown",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": null,
    "priority": 60,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-review",
    "reviewNote": "Booking state or studio mapping requires review; no active homepage button.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "chicago-pipe-and-ashtray",
    "title": "Pipe & Ashtray Making",
    "description": "Shape your own ceramic pipe and ashtray by hand.",
    "acuityTitle": "Pipe and Ashtray Making Class - Chicago",
    "appointmentTypeId": 79188421,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79188421",
    "priority": 12,
    "adultThemed": true,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[36]
  },
  {
    "key": "eugene-pipe-and-ashtray",
    "title": "Pipe & Ashtray Making",
    "description": "Shape your own ceramic pipe and ashtray by hand.",
    "acuityTitle": "Eugene Pipe and Ashtray Making Class",
    "appointmentTypeId": 90211026,
    "calendarIds": [
      13582962
    ],
    "city": "eugene",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=90211026",
    "priority": 12,
    "adultThemed": true,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[19]
  },
  {
    "key": "chicago-boobs-mug",
    "title": "Boobs Coffee Mug",
    "description": "Handbuild a cheeky, body-inspired ceramic mug.",
    "acuityTitle": "Boobs Coffee Mug - Chicago",
    "appointmentTypeId": 79187550,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79187550",
    "priority": 21,
    "adultThemed": true,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[1]
  },
  {
    "key": "chicago-dildos-and-bottles",
    "title": "Dildos Pottery",
    "description": "Sculpt a playful adult-themed creation from clay.",
    "acuityTitle": "Dildos and Bottles - Chicago",
    "appointmentTypeId": 79186927,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79186927",
    "priority": 30,
    "adultThemed": true,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[13]
  },
  {
    "key": "chicago-pussy-pottery",
    "title": "Pussy Pottery",
    "description": "Create expressive, body-inspired ceramic art.",
    "acuityTitle": "Pussy Pottery - Chicago",
    "appointmentTypeId": 79188691,
    "calendarIds": [
      12216179
    ],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=79188691",
    "priority": 41,
    "adultThemed": true,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[37]
  },
  {
    "key": "chicago-acuity-96857633",
    "title": "The Royal Mold Dildo Making Workshop",
    "description": "Private event No glaze included",
    "acuityTitle": "The Royal Mold Dildo Making Workshop",
    "appointmentTypeId": 96857633,
    "calendarIds": [],
    "city": "chicago",
    "mode": "in-person",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=96857633",
    "priority": 95,
    "adultThemed": true,
    "ageRestriction": null,
    "beginnerFriendly": null,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "online-online-cauldron",
    "title": "Live Online Cauldron Pottery",
    "description": "Make a clay cauldron in a guided workshop from home.",
    "acuityTitle": "Make a Clay Cauldron — Live Online Halloween Workshop",
    "appointmentTypeId": 98770334,
    "calendarIds": [
      12216179
    ],
    "city": "online",
    "mode": "online",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=98770334",
    "priority": 100,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "ready",
    "reviewNote": null,
    "verifiedAt": "2026-10-05",
    "image": APPROVED_PHOTOS[28]
  },
  {
    "key": "online-online-pottery",
    "title": "Live Online Pottery Course",
    "description": "Learn pottery over six weeks with live online instruction.",
    "acuityTitle": "6-Week Live Online Pottery Course + Wheel Kit",
    "appointmentTypeId": 97904203,
    "calendarIds": [
      12216179
    ],
    "city": "online",
    "mode": "online",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97904203",
    "priority": 101,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
  {
    "key": "online-online-watercolor",
    "title": "Live Online Watercolor",
    "description": "Explore watercolor with live guidance from your instructor.",
    "acuityTitle": "Live Online Watercolor Class for All Levels with Feerozeh",
    "appointmentTypeId": 97904869,
    "calendarIds": [],
    "city": "online",
    "mode": "online",
    "detailUrl": null,
    "bookingUrl": "https://colorcocktailfactory.as.me/?appointmentType=97904869",
    "priority": 102,
    "adultThemed": false,
    "ageRestriction": null,
    "beginnerFriendly": true,
    "byob": null,
    "eligibility": "needs-photo",
    "reviewNote": "No suitable activity-specific approved photograph was available in the supplied folder.",
    "verifiedAt": "2026-10-05",
    "image": null
  },
];
